Migrated to React
porky-arania/todo pull request #25
Opened 2023-03-08 18:31 UTC by Mariano-Soffredi

2023-03-11 15:14 UTC, Esequiel378 requested changes
Awesome job, guys! :raised_hands: 

I left some comments to address some of the issues/changes that I've posted can be found in multiple files. Please make sure to review all the files to see them.

PS: I intentionally omitted some of them so you can exercise finding bugs or parts of the code to improve. Happy hunt! :deer:

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/edit/edit.jsx
> +            setTimeout(() => {
Watch out! This timeout is not cleared.

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/edit/edit.jsx
> +          onClick={() => {
A common pattern. is to create the onClick handlers as functions outside the jsx to keep the UI part of the code as clean as posible

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/edit/edit.jsx
> +            onKeyUp={e => {if(e.keyCode === 13) {
You can check for `e.keyCode !=== 13` and use an early return to keep the code clean. Also, what does 13 mean? Avoid magic numbers! Abstract this into a constant indicating what it is.

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/edit/task.jsx
> +    <div key={task._id} className='todo-task' onClick={e => {
React has a hook called useRef. It can come in handy in this situation.

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/edit/task.jsx
> +          debounce(api.updateTodo(todo, setTodo, setTodos), 800);
Excellent use of debounce! :raised_hands:

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/login/login.jsx
> +  const fetchUrl = () => signup ? '/signup' : '/signin';
I think creating a variable inside of `sendData` is a better approach.

```jsx
const sendData = async (e) => {
  e.preventDefault();
  const URL = singup ? '/signup ': ''/signin;
  ...
}
```

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/login/login.jsx
> +    if (errors) {
I don't see the need to use the conditional here. You can use `error?.email` to make sure you don't have an error if `error` is `null/undefined`

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/pages/login/login.jsx
> +  if (signup) {
Excellent use of early return :raised_hands:

2023-03-11 15:14 UTC, Esequiel378 commented on frontend/src/sidebar/filters.js
> +  'All': (todo) => todo,
You don't need the quotes around the keys here

2023-03-16 14:37 UTC, Esequiel378 requested changes
Excellent work, guys! Just a few changes to made :raised_hands:

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/api/api.js
> +    .finally(() => this.getTodos().then(todos => setTodos(todos)));
Have you tested this part of the code? When using `this` in an arrow function, it points to `window`, which will be translated to `window.getTodos`.

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/modal/ModalTemplate.jsx
> +function Modal(props) {
It is a common practice to destructure the props.

```jsx
function Modal({ close, title, content }) {
    ...
}
```

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/modal/ModalTemplate.jsx
> +    <div className='modal' hidden={props.hidden} onClick={props.close}>
I would recommend using a `<dialog>` element instead. It gives a lot of functionality out of the box.

[Modals made easy](https://www.youtube.com/watch?v=TAB_v6yBXIE&t=269s&ab_channel=KevinPowell)
[Styling modal](https://www.youtube.com/watch?v=RO40Opyizeg&ab_channel=KevinPowell)

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/pages/edit/edit.jsx
> +    const interval = setInterval(() => {
Have you looked into CSS animations? Not sure, but maybe it can help here.

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/pages/edit/edit.jsx
> +            onKeyUp={e => {if(e.key === 'Enter') createTask()}}
If you are using if, please break it down into multiple lines, and use on-liners with the shorthand.

```jsx
onKeyUp={e => e.key === 'Enter' && createTask()}
```

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/pages/home/new-todo/new-todo.jsx
> +    const title = document.querySelector('.modal-input').value;
Do not use `querySelector`; that breaks the purpose of React. If you are unsure how to work around this, let's set up a meeting to discuss this.

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/sidebar/sidebar.jsx
> +  const filtersKeys = Object.keys(props.filters);
I suggest using the `useMemo` hook.

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/sidebar/sidebar.jsx
> +            return (
Generally, we don't need to use the return keyword here. Just remove it and the curly braces too.

2023-03-16 14:37 UTC, Esequiel378 commented on frontend/src/sidebar/sidebar.jsx
> +            return (
Same as above.

2023-03-21 19:05 UTC, FranMaggi73 commented on frontend/package.json
> +    "@testing-library/jest-dom": "^5.16.5",
it will be implemented in the next project

2023-03-29 23:41 UTC, Esequiel378 approved these changes
Awesome work! :muscle:

2023-03-29 23:42 UTC, merged